#pragma once
#include "order_book.hpp"
#include <vector>
#include <deque>
#include <cmath>
#include <numeric>
#include <algorithm>

// ----------------------------------------------------------------
// MatchingEngine
//
// Thin wrapper around OrderBook that:
//   - Assigns timestamps
//   - Provides round-to-tick price quantisation
//   - Computes derived statistics: VWAP, realised volatility
//   - Tracks fill history and mid-price history
// ----------------------------------------------------------------
class MatchingEngine {
public:
    explicit MatchingEngine(double tick_size = 0.01);

    // ------ Order submission (the API exposed to Python) ---------
    // Returns vector of fills generated by the order.
    // `trader_id` is optional; -1 = anonymous.
    std::vector<Fill> submit_limit (Side side, double price,
                                    int qty, int trader_id = -1);
    std::vector<Fill> submit_market(Side side, int qty, int trader_id = -1);
    bool              cancel_order (uint64_t order_id);
    uint64_t          last_order_id() const { return last_order_id_; }

    // Generic dispatcher (for internal use / process() interface)
    std::vector<Fill> process(Order& order);

    // ------ Book state getters -----------------------------------
    double best_bid()  const { return book_.best_bid();  }
    double best_ask()  const { return book_.best_ask();  }
    double mid_price() const { return book_.mid_price(); }
    double spread()    const { return book_.spread();    }
    double ofi()       const { return book_.order_flow_imbalance(); }

    std::vector<std::pair<double,int>> bid_levels(int depth) const
        { return book_.bid_levels(depth); }
    std::vector<std::pair<double,int>> ask_levels(int depth) const
        { return book_.ask_levels(depth); }

    int total_bid_volume(int levels = 10) const
        { return book_.total_bid_volume(levels); }
    int total_ask_volume(int levels = 10) const
        { return book_.total_ask_volume(levels); }

    // ------ Derived statistics -----------------------------------
    double vwap(int n_last_fills) const;
    double realized_volatility(int window) const;

    // ------ History access ---------------------------------------
    const std::vector<Fill>& fill_history()      const { return fill_history_; }
    const std::deque<double>& mid_price_history() const { return mid_history_; }

    // Direct book access (e.g., for testing)
    OrderBook& book() { return book_; }

private:
    OrderBook         book_;
    std::vector<Fill> fill_history_;
    std::deque<double> mid_history_;    // capped at max_mid_history_
    double            tick_size_;
    uint64_t          round_       {0};
    uint64_t          last_order_id_ {0};
    static constexpr int max_mid_history_ = 2000;

    double round_to_tick(double price) const;
    void   record_fills (const std::vector<Fill>& fills);
    void   record_mid   ();
};
